### ISSUE TITLE
Unable to login to webconsole using OAuth

### ISSUE THREAD

**Issue by kornys** [EnMasseProject/enmasse#1113]
When I try to open webconsle from different server on same subnet as server running the openshift webbrowser cannot reach the keycloak because it tries to redirect me to service IP.

Env:
- Server running openshift with enmasse
- WebBrowser running on different system in same subnet

Steps to reproduce:
1. Deploy enmasse and create address space
2. Try open and login webconsole using webbrowser

**Comment by kornys** [comment]
https://github.com/EnMasseProject/enmasse/pull/1109

**Comment by grs** [comment]
oauth is not yet supported in the address-controller for an external auth service either. In that case I guess it would be a new field in the address-space definition. That same field could perhaps be optionally used to provide the value even for the 'standard' auth service type, with the current cobbling together merely a fallback (to avoid having to specify it). Possibly it would even be cleaner to derive the default url if not specified somewhere else (since its the address-controller that sets up the route anyway). I did not have the big picture for this component, so made a 'pragmatic'(!) hack to get it working.
