### ISSUE TITLE
Add support for watching addressspaces and addresses to api server

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#1280]
This is required in order to use the API server by our controller components. This is a required step in the direction of introducing alternative persistence for address spaces and addresses.

**Comment by secondsun** [comment]
I'm working on an operator that uses enmasse and having this would be really useful.  We'd like to be able to recreate queues / topics if they are deleted.  Currently we can, but something else has to trigger the reconcile loop, and I would like to be more reactive.

**Comment by secondsun** [comment]
Update: So this problem is actually really bad if you use enmasse in a golang operator client.  In k8s watches are sent to controllers with a truthy `watch` as a query parameter and the response is a stream of `WatchEvents`.  In the enmasse controller instead the `$RESOURCEList` result is returned (ie AddressList, AddressSpaceList, etc).  In client go this is reported as a error and the goroutine is relaunched.  This relaunched goroutine immediately fails and logs an error and relaunches.  Infinitely.

Additionally if you set an owner and controller to Addresses etc then when those resources are created in your namespace this behavior kicks off as well.

**Comment by kornys** [comment]
api-server was removed from enmasse
