### ISSUE TITLE
Refactor MQTT gateway and LWT unit tests to run without router

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#134]
The unit tests for mqtt-* components currently start up the router in a docker image. This causes some test unstability on travis, and I'm not sure how much value those tests add when we have systemtests as well.

Wdyt @ppatierno ?

**Comment by ppatierno** [comment]
My opinion is that we can remove to run this tests on Travis CI (so no starting up the router image) but not removing the tests from the projects. I have used them a lot during development and I think that it could be useful during the development process (because I don't use systemtests in that phase).

**Comment by lulf** [comment]
Closing as this was fixed a while ago.
