### ISSUE TITLE
Service-broker contains stale route to console

### ISSUE THREAD

**Issue by robshelly** [EnMasseProject/enmasse#1484]
**What**
Remove the route to the console from the service-broker

**Why**
This link appears to be stale. Currently, links to the console are created when an address space is created and each link is unique to it's address space. Therefore this link is invalid and should be removed.

**How**
See [ansible role](https://github.com/EnMasseProject/enmasse/blob/master/templates/install/ansible/roles/service_catalog/tasks/main.yml) where route is created.

**Comment by lulf** [comment]
This route is used by the service broker to provide a known dashboard URL for the address space in the OpenShift UI before the actual URL is known (i.e. after the route is created by the address-space-controller. We don't know at address space creation what the console hostname will be, because that is defined by the OpenShift infrastructure.).

 I.e. address space 'foo' will be redirected to 'https://<console url>/foo' which will redirect to the namespaced console url.

**Comment by lulf** [comment]
Closing after discussing the reason for the issue.
