### ISSUE TITLE
Allow EnMasse to use the same Keycloak instance as the OpenShift cluster it's running in

### ISSUE THREAD

**Issue by david-martin** [EnMasseProject/enmasse#1539]
Currently, EnMasse depends on its own Keycloak instance.
If EnMasse is installed on an Openshift cluster with a number of other middleware products, the goal is to have a single Keycloak instance that OpenShift, EnMasse and all other products use for auth.
A User would have a single identity and use (seamless) single sign on to access the consoles of each of the products, EnMasse included.
From and operations point of view, there will only be 1 Keycloak instance in the OpenShift cluster to manage, which means 1 single source of User identity.

Some challenges I'm aware of with this:

* there are some keycloak plugins being used by EnMasse
* there is an openshift identity provider, which uses a ServiceAccount OAuth Client in the same project as EnMasse for authentication
* EnMasse creates realms on the fly

**Comment by rgodfrey** [comment]
> From and operations point of view, there will only be 1 Keycloak instance in the OpenShift cluster to manage, which means 1 single source of User identity.

So, I think we need to distinguish between console/cli "users" and messaging users.  EnMasse treats these as conceptually identical - the identities coming from a single source.  Secondly EnMasse also stores authorisation permissions for users **_per addressspace_** for the users.  Even if we are using a single keycloak (and presumably by this you actually mean a single keycloak realm) as a single source of identity, we would still want to separate out the permissions between different address spaces.  Just because a messaging user "client" has permission to send messages to queue "foo" in address space "A", doesn't mean they should be able to do so in address space "B".  Moreover the messaging user "client" in address space "A" should be a conceptually different entity from a messaging user "client" in address space "B".

Issues #1533 and #1534 will tidy up the user experience for the "console" user considerably.  To go beyond this I think we need to decide how we are going to manage authorisation/access control for "OpenShift" users to the console (if I want to give "J Smith" access to the console, but only to view not to modify, how can I do that... Right now in EnMasse I can add the user in the distinct Keycloak realm and give only the required permissions... how would I do that in the "single keycloak" case), and then we need to work out how to solve the "messaging users" problem...  Ideally I guess we'd want a generalised way of creating "sub-accounts" and managing permissions across apps on the cluster

**Comment by rgodfrey** [comment]
Console now uses Openshift/Kubernetes for identity/authorisation
