### ISSUE TITLE
Create systemtests for different cert providers

### ISSUE THREAD

**Issue by lulf** [EnMasseProject/enmasse#1814]
We should have a `CertProviderTest` that creates addressspaces and selecting different cert providers for address space endpoints once #1668  is merged. This will create an `openshift` and `certBundle` cert provider in addition to the default `self-signed` cert provider.

**Comment by famartinrh** [comment]
@lulf I'm preparing the test plan for this, how do you think we should assert each cert provider is working properly? just connect and use services normally?
For now I noticed a first change needed in systemtests because we are trusting all certificates in client connections. 
https://github.com/EnMasseProject/enmasse/blob/b58c926ae6c9f863a317c3ecc1ed49702306737c/systemtests/src/main/java/io/enmasse/systemtest/amqp/AmqpClientFactory.java#L84-L95
Other thing I wonder... the only case we need server cert for client connections and don't trust all certificates is in case of provider=certBundle, right?

**Comment by lulf** [comment]
@famartinrh Yes, basically connect to services and ensure that you can trust the CA. I.e.

* For certBundle provider, trust the CA you used to create the cert. Trusting this CA and connecting successfully validating the cert means success.
* For openshift provider, trust the OpenShift cluster CA. Same success criteria as above
* For selfsigned provider, trust the cert in address space status

Note that for openshift provider, client should run on openshift.
