### ISSUE TITLE
Console redeploys after first addressspace is created

### ISSUE THREAD

**Issue by vbusch** [EnMasseProject/enmasse#2759]
On a new EnMasse deployment, create the first addressspace. The console shows the address space in pending.  Then it disappears.
It disappears, because when the very first address space is created, "ssoCookieDomain: .127.0.0.1.nip.io" is added to the consoleservice crd.  Which causes a redeployment of the console.

**To Reproduce**
1. Have a new install of EnMasse.
2. In the global console create a new address space.  (Or add "ssoCookieDomain: .127.0.0.1.nip.io" to the console crd manually.)
3. Watch as the console is undeployed and redeployed.

**Expected behavior**
Should be able to create the first addressspace, without the console being redeployed.

**Comment by k-wall** [comment]
The  algorithm works for determining the `ssoCookieDomain`  works by looking at the commonality between the FQDNs applied to the global console and address space console(s).  If the operator detects a common suffix, it adjusts the ssoCookieDomain so that the cookie is readable by all the webapps.  It needs the appearance of the first addresss space console in order to trigger this processing.

I would have expected the default kubernetes rolling update to handle this gracefully.  New traffic should not be let into the replacement instance of the global console until the instance is 'ready' according to the readiness probes.  It might be the lack of the readiness probes on the HTTPD container has some bearing.   Current HTTPD binds only to loopback, so I didn't define a readiness probe for it.
