### ISSUE TITLE
Upgraded addressspaces are not shown active in Console

### ISSUE THREAD

**Issue by k-wall** [EnMasseProject/enmasse#2865]
**Describe the bug**
I upgrade EnMasse from 0.26.6 to 0.28 with an existing (standard) addressspace by applying the new bundle.

**To Reproduce**
1. Install 0.26.6
2. Create a standard address space and one queue address
3. Upgrade to 0.28.  

**Expected behavior**
After upgrade I expect the existing addressspace to be available in the Console.  The addresspace is showing the Console, but it is marked with a red X.

The issue is that the controller is not assigned the phase Active.

**Comment by lulf** [comment]
@k-wall some background here as welll ... 😅 I made the phase field optional at the time of introduction, because 0.27 would not allow unknown fields in the schema, and therefore rolling back from a failed upgrade (0.27->0.28->0.27 ) would break. 

The trade off I chose was to set the phase field on new address spaces, leaving the existing ones untouched. Unfortunately I did not consider the implication of the console at the time.

My intention was to make the phase field always be there in 0.29 and onwards.

**Comment by k-wall** [comment]
> @k-wall some background here as welll ... 😅 I made the phase field optional at the time of introduction, because 0.27 would not allow unknown fields in the schema, and therefore rolling back from a failed upgrade (0.27->0.28->0.27 ) would break.
> 
> The trade off I chose was to set the phase field only on new address spaces, leaving the existing ones untouched. Unfortunately I did not consider the implication of the console at the time.
> 
> My intention was to make the phase field always be there in 0.29 and onwards.

@lulf thanks again for the reply.  I think if we truly what to support downgrade, then we need to be prepared to ship a script that undoes the actions of the upgrade.  I think trying to write everything so we can just fall back won't be tenable.  I think our goals should be ensuring if an upgrade fails it should strive to leave the system in a state where restarting will continue the upgrade process without manual intervention.
