### ISSUE TITLE
Docs: add "build publish" function to upstream build

### ISSUE THREAD

**Issue by jenmalloy** [EnMasseProject/enmasse#3082]
When rearranging content, it would be helpful to be able to publish a local docs build so reviewers can more easily see the built updated content. (So, add `make publish` capability, I think?)
For reference: https://strimzi.io/contributing/guide/#make-tooling

**Comment by lulf** [comment]
@jenmalloy 

We can add some additional make targets based on that doc if that makes it more convenient, but you'd still need to point it to a server where you have access in order to publish them (see the PUBLISH_DEST explanation in the link).

So, we could add a documentation/Makefile, and you would be able to "cd documentation" and run `make check`, `make publish` etc, but you'd still need a server to publish to.
