### ISSUE TITLE
Current installation is incompatible with Online Pro or developer usage

### ISSUE THREAD

**Issue by thesteve0** [EnMasseProject/enmasse#676]
The current OpenShift install instructions assumes I can login as system:admin. This is not the case for most developers. To be clear this is a **blocker** for any evaluation by developers on any hosted OpenShift instance (OCP and Pro). The only place a developer could even try this now is on minishift. 

The install procedures can not require elevated privileges.
_From the install instructions:_
Create cluster-wide roles used by the enmasse-admin service account:

oc login -u system:admin
oc create -f ./openshift/cluster-roles.yaml

Grant cluster-admin privileges to service account:

oc login -u system:admin
oc adm policy add-cluster-role-to-user enmasse-namespace-admin system:serviceaccount:en

**Comment by lulf** [comment]
It is not the intention that EnMasse will be installed in an OpenShift Online Free/Pro environment. Instead, those environments can offer a messaging service in the service catalog (in the same way Amazon services are exposed today). The actual EnMasse install might run on a different OpenShift cluster and only exposed via the enmasse service broker. Think of EnMasse not as an OpenShift template that you deploy and manage in your own namespace, but as an AWS service infrastructure and that your application interacts with that service.

For OCP though, wouldn't you be the cluster admin? Or are you saying that the evaluation version on https://www.openshift.com/container-platform/trial.html have some additional restrictions?

That being said, it is possible to deploy all of EnMasse within a single OpenShift project as long as you only create a single address space in the same namespace the address controller is running. This is not covered by the install instructions though since it would not support multiple address spaces for instance.

As we will be moving to use custom resource definitions for EnMasse, I wonder if you can even create those without being cluster admin. We might be offering a template to deploy a single address space that doesn't rely on the address-controller in the future, but it would still require CRDs to work.

**Comment by thesteve0** [comment]
CRDs?

In terms of online, yeah I understand that is the intended final use case
but what should I do until then if I want to use it is somewhat real
scenarios?

For a developer trying to evaluate enMasse they will likely not have their
own OCP cluster with admin privs. So if we can keep everything in one
namespace/project that would be fine for now.

Is there a doc on understanding the "single versus multiple address
spaces". If so then we could give the instructions for a single project and
point to the doc to explain what they won't get with single project.

Thanks

**Comment by lulf** [comment]
CRDs https://kubernetes.io/docs/concepts/api-extension/custom-resources/ (It will allow you to declaratively state address spaces and addresses as kubernetes resources, and use the standard command line tools like kubectl/oc to manipulate them. Today we store them as configmaps and provide a REST api to manipulate them)

I agree we should probably document the 'self-contained' deployment mode a bit better. Right now the unix-only script in the getting started guides uses this mode and should work without system admin privileges: http://enmasse.io/documentation/0.15.3/#enmasse-on-openshift

Technically, there is no difference between these modes, so we can add some hints to the documentation. The reason for requiring system:admin privileges is that if you create an address space in a namespace that is not the same as where you deployed enmasse, it will require additional privileges to create and manage resources in that namespace.

By simply installing enmasse in 'myproject' as in the installation guide, and create an address space with its namespace set to 'myproject', no additional privileges should be required.

**Comment by thesteve0** [comment]
Hey @lulf thanks for all the help and sorry for the delay (flu). 

So are you saying I can skip the system:admin steps if I install enmasse in a namespace I created for it and then only use it in that namespace?

What is an address space? Is that something I set later - sorry been a few days since I looked at the doc.

**Comment by lulf** [comment]
> So are you saying I can skip the system:admin steps if I install enmasse in a namespace I created for it and then only use it in that namespace?

Yes, that's what I'm saying. 

You can create an address space after doing the multitenant 'install', follow http://enmasse.io/documentation/0.15.3/#configuring-using-restapi

It is important that the 'namespace' field in the address space definition is the same as where you did the install.

For a generic explanation of address spaces: http://enmasse.io/documentation/0.15.3/#address_model

Basically, a tenant/openshift user may create multiple address spaces and create addresses within each address space. They are isolated, so addresses in address space A are not accessible from address space B. Each address space has a route associated with them for clients to connect to. 

In the future, we plan to offer a bridging feature which would allow you to map addresses from one address space into another (potentially running in a different region).

**Comment by lulf** [comment]
Docs for single tenant use have been added and are used
