### ISSUE TITLE
Inactive autolinks for enmasse address of type "queue pooled-persisted" 

### ISSUE THREAD

**Issue by DanielMaier-BSI** [EnMasseProject/enmasse#806]
Hi,

I am not sure if this is related to #736: We create 14 addresses of type "queue pooled-persisted", all these addresses appear in enmasse REST API as ready. However in artemis there are no consumers AND producers for 3 of the corresponding queues. For 2 of the addresses there is even no queue at all in artemis. Addresses without producers and consumers are event/DEFAULT_TENANT,  event/HUB_TEAM_TENANT and event/PERF_TEST_TENANT. Addresses without queues at all are event/PERF_TEST_TENANT and event/HUB_TEAM_TENANT.

What I can see is that autolinks for these addresses are inactive. Please refer to the attached qdstat outputs.

[qdstat.txt](https://github.com/EnMasseProject/enmasse/files/1667774/qdstat.txt)

Thanks
Daniel

**Comment by lulf** [comment]
What version are you using?

**Comment by DanielMaier-BSI** [comment]
Sorry, forgot to mention used version. We are using 0.16.0-rc2.

**Comment by lulf** [comment]
@DanielMaier-BSI Ok, thanks.  Even if the rest api states 'ready=true', the queue scheduler might not have created the queues and connectors yet, so this could happen. However, it should only be temporary, so do the consumers and producers turn up after a while? If not, it would be useful to view the logs of the queue-scheduler as well as the broker logs.

**Comment by DanielMaier-BSI** [comment]
No, they don't turn up for hours. So I think they would not appear again :). Here are the logs 
 


[logs-from-queue-scheduler-in-admin.txt](https://github.com/EnMasseProject/enmasse/files/1667933/logs-from-queue-scheduler-in-admin.txt)
[logs-from-broker-in-pooled-persisted.txt](https://github.com/EnMasseProject/enmasse/files/1667934/logs-from-broker-in-pooled-persisted.txt)

**Comment by lulf** [comment]
I think I have an explanation of what is happening:

1. Creating the connector service of event/DEFAULT_TENANT fails due what looks like a threading issue. The queue create is however successful. The other addresses do not exist because this first operation failed.

2. Second attempt at creating the queues and connectors for event/DEFAULT_TENANT fails because the getQueueNames() times out. This could be due to a too low timeout, and is actually configurable. If you can, it would be interesting if you could edit the admin deployment, and for the 'queue-scheduler' container add an environment variable DEFAULT_BROKER_REQUEST_TIMEOUT = 30 to the config.

Why this call fails I think is not clear, but i'd bet on it being GC since the broker is being so silent about things. If the system is still running, add an environment variable to the 'pooled-inmemory' deployment with JAVA_OPTS=-verbose:gc to check. The reason I think GC is that the 'auto-adjust java heap based on container limits' was fixed, but since the default container limit is 512MB, the broker will get a heap of 256M.  

So there are a couple of fixes I'd like to do before creating another rc:
1. Investigate threading issue, but this might not be worth spending too much time on since the component will be replaced in the next release.
2. Ensure queue-scheduler is able to recreate connectors/queues at the controller iteration even if only the queue got created (i suspect this would break as the code works now, and fixing should be simple).
3. Bump default broker container limits to 2GB, giving the broker 1GB of heap by default, which I think is more than reasonable since it can host many queues.
4. Consider increasing the default timeouts a little (but not sure about that as I think having it low allows us to discover the issue much earlier).

**Comment by calohmn** [comment]
Log improvement: In this line from above log
> 2018-01-26 08:25:27 ERROR QueueScheduler:152 - Error handling address change
java.util.concurrent.TimeoutException: Timed out getting response from broker pooled-persisted-7c949559f4-4nvjv on broker.createConnectorService with parameters: [Ljava.lang.Object;@3f67181a

it would be good to see the contents of the `parameters` array.

**Comment by lulf** [comment]
@DanielMaier-BSI @calohmn I've created an RC3 with some fixes. Unfortunately, the travis CI build fails with a larger broker limit as default. In 0.17.0, it will be possible to configure this memory limit at run time.

You can, however, modify it at 'deploy time' in rc3 by editing the kubernetes/enmasse.yaml and replace the value for BROKER_MEMORY_LIMIT  (set to "512Mi" in the template) to "2Gi" for instance. This will provide the broker with more memory.

**Comment by calohmn** [comment]
@lulf Thanks for the quick update.
In the RC3 build there seems to be a general issue with the pooled-persisted pod though - see #814.

**Comment by lulf** [comment]
@calohmn Please try RC 4:

https://github.com/EnMasseProject/enmasse/releases/download/0.16.0-rc4/enmasse-0.16.0-rc4.tgz

**Comment by DanielMaier-BSI** [comment]
looks good to me.

Thanks @lulf
