### ISSUE TITLE
receiver is not able to receive messages afte scale down

### ISSUE THREAD

**Issue by tkratky** [EnMasseProject/enmasse#851]
reproducer:
1. create Queue 'scalequeue' with plan 'sharded-queue' in 'standard' address space with plan 'unlimited-standard'
2. scale up 'scalequeue' to 4 replicas
3. send 4k messages
4. receive 500 messages
5. scale down 'scalequeue' to 1 replica
6. receive remaining messages (failed on timeout)

reproducible via automated test: (test is temporarily disabled) 
`make MULTITENANT=true SYSTEMTEST_ARGS='io.enmasse.systemtest.standard.QueueTest#testScaledown' systemtests`

By 'oc get pv' command it looks like no persistent storage is used for broker with this plan. May I change it somewhere?

**Comment by tkratky** [comment]
@lulf this issue should be fixed by this commit? https://github.com/EnMasseProject/enmasse/commit/e007387ea337c21bc8ebb057356edd571f4e8ef4

**Comment by lulf** [comment]
@tkratky no, persistence has nothing to do with scaledown actually. I'll try to have a look at this today.

**Comment by lulf** [comment]
@tkratky @grs @rgodfrey Scaledown is a bit strange with sharded queues right now. The way the test scales up brokers won't work, because the standard-controller will scale the replicas back to the amount of credit. Since the number of replicas are dictated by the plans, this means that a queue to be sharded across 4 brokers needs to use a plan with broker credit = 4. 

This also means that in order to scale down, an address needs to be able to change plan to one with fewer credits. I've not tested that, but I believe it to be possible as long as the plan exists at the time of creating the address space.

@tkratky This means the test needs to add an extra plan (perhaps this is something we should add to the plans out of the box) for a sharded queue consuming more than 1 broker. Then to scaledown, the address needs to be changed. I'm not completely sure if that will work right now, but I think thats the mechanism we should use.

**Comment by tkratky** [comment]
@lulf aha, thanks for the answer. I created new issue for modification QueueTest. 
How should we test persistent addresses? Can I define persistent addresses via plan. (it could be nice feature, what do you think?)
