### ISSUE TITLE
Document swagger spec URI and consider providing UI

### ISSUE THREAD

**Issue by ctron** [EnMasseProject/enmasse#943]
EnMasse already has a swagger spec file [1]. So it would be helpful if the file is also serviced by the REST endpoint. So it would be possible to use it with [2]

Of course EnMasse could also deploy its own instance of Swagger UI and provide the experience out of the box without the need to resort to an external service.

[1] https://github.com/EnMasseProject/enmasse/blob/master/address-controller/src/main/resources/swagger.json
[2] http://petstore.swagger.io/

**Comment by lulf** [comment]
It appears we already have a swagger endpoint if you go to the rest api path /swagger.json actually! However, I'm not sure if this is the ideal place for it + we should document it so that I don't misinform people asking about it :)

Moreover I think it would be good for it to be generated dynamically rather than statically like today.

Running the UI could be an interesting configuration option but not something I'd invest heavily into at the moment.

**Comment by lulf** [comment]
@ctron The swagger spec has been updated to reflect the 'official' REST API now. I've also setup swagger2markup to generate an asciidoc REST API reference. This is currently available on http://enmasse.io/documentation/master/#rest_api_reference

If you think this is sufficient for now, maybe we can close this?
